### ISSUE TITLE
HELP! A error when testing

### ISSUE THREAD

**Issue by csEylLee** [CAMMA-public/rendezvous#13]
Test weight used:  ./__checkpoint__/run_2/rendezvous_l8_cholectcholect50_k0_batchnorm_lowres.pth
Traceback (most recent call last):
  File "/home/cv5/rendezvous_code/pytorch/run_update.py", line 464, in <module>
    mAP_i = mAPi.compute_video_AP(ignore_null=set_chlg_eval)
  File "/home/cv5/anaconda3/envs/torch110/lib/python3.8/site-packages/ivtmetrics/recognition.py", line 189, in compute_video_AP
    classwise = average_precision_score(targets, predicts, average=None)
  File "/home/cv5/anaconda3/envs/torch110/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 234, in average_precision_score
    return _average_binary_score(
  File "/home/cv5/anaconda3/envs/torch110/lib/python3.8/site-packages/sklearn/metrics/_base.py", line 72, in _average_binary_score
    raise ValueError("{0} format is not supported".format(y_type))
ValueError: multiclass-multioutput format is not supported

**Comment by TheBlackCat22** [comment]
Are you using the CholecT50 dataloader ?

**Comment by csEylLee** [comment]
> Are you using the CholecT50 dataloader ?

Yes. I've solved it now.
