### ISSUE TITLE
Cannot training

### ISSUE THREAD

**Issue by Ving2k2** [CAMMA-public/rendezvous#16]
C:\Users\ADMIN\anaconda3\envs\myenv\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: [WinError 127] The specified procedure could not be found
  warn(f"Failed to load image Python extension: {e}")
Configuring network ...
Traceback (most recent call last):
  File "C:\Users\ADMIN\PycharmProjects\rendezvous\pytorch\run.py", line 304, in <module>
    dataset = dataloader.CholecT50( 
  File "C:\Users\ADMIN\PycharmProjects\rendezvous\pytorch\dataloader.py", line 102, in _init_
    self.build_train_dataset(trainform)
  File "C:\Users\ADMIN\PycharmProjects\rendezvous\pytorch\dataloader.py", line 172, in build_train_dataset
    target_transform=self.target_transform)
AttributeError: 'CholecT50' object has no attribute 'target_transform'

Hi,
I have some problem when training the model. I use the dataloader.py in the repo CholecT50 of you. Do you have any suggest ? Thank you

**Comment by csEylLee** [comment]
You should use the dataloader_pth.py in cholect50 repository.
